name: Documentation
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Deploy docs
        run: uv run mkdocs gh-deploy --force
